// QR Code Configuration for Even Hospital
// Each QR code maps to a type + id combination

// ── ROOM MAPPINGS ──────────────────────────────────────────────────
// Maps QR IDs to room details. Room QR shows the full patient view.
export const ROOM_QR_MAP = {
  '102': { room: '102', floor: '1st Floor', wing: 'East', type: 'General Ward' },
  '203': { room: '203', floor: '2nd Floor', wing: 'East', type: 'General Ward' },
  '205': { room: '205', floor: '2nd Floor', wing: 'East', type: 'General Ward' },
  '215a': { room: '215 a', floor: '2nd Floor', wing: 'West', type: 'General Ward' },
  '215b': { room: '215 b', floor: '2nd Floor', wing: 'West', type: 'General Ward' },
  '310a': { room: '310 a', floor: '3rd Floor', wing: 'East', type: 'Private Room' },
  '310b': { room: '310 b', floor: '3rd Floor', wing: 'East', type: 'Private Room' },
  '401': { room: '401', floor: '4th Floor', wing: 'West', type: 'Suite' },
  'icu-1': { room: 'ICU Bed 1', floor: '1st Floor', wing: 'Central', type: 'ICU' },
  'icu-2': { room: 'ICU Bed 2', floor: '1st Floor', wing: 'Central', type: 'ICU' },
};

// ── LOCATION QR CONFIGURATIONS ─────────────────────────────────────
// Each location has a custom page with specific options
export const LOCATION_QR_MAP = {
  'coffee-machine': {
    name: 'Coffee Machine',
    subtitle: '2nd Floor Hallway',
    icon: '☕',
    color: '#92400e',
    bg: '#fffbeb',
    allowPhoto: true,
    allowFreeText: true,
    requireIdentification: false,
    categories: [
      { id: 'machine-broken', name: 'Machine Not Working', icon: '🔧', dept: 'Maintenance', assignee: 'Raju', slaMin: 30 },
      { id: 'no-cups', name: 'No Cups Available', icon: '🥤', dept: 'Housekeeping', assignee: 'Abu', slaMin: 15 },
      { id: 'no-water', name: 'No Water / Low Supply', icon: '💧', dept: 'Maintenance', assignee: 'Raju', slaMin: 30 },
      { id: 'coffee-quality', name: 'Poor Coffee Quality', icon: '👎', dept: 'FnB', assignee: 'Rohit Singh', slaMin: 45 },
      { id: 'spill-cleanup', name: 'Spill / Needs Cleaning', icon: '🧹', dept: 'Housekeeping', assignee: 'Abu', slaMin: 20 },
      { id: 'machine-dirty', name: 'Machine Dirty', icon: '🧽', dept: 'Housekeeping', assignee: 'Abu', slaMin: 30 },
    ],
  },
  'hallway-2f': {
    name: 'Common Area',
    subtitle: '2nd Floor Hallway',
    icon: '🏥',
    color: '#0369a1',
    bg: '#f0f9ff',
    allowPhoto: true,
    allowFreeText: true,
    requireIdentification: false,
    categories: [
      { id: 'ac-issue', name: 'AC Not Working', icon: '❄️', dept: 'Maintenance', assignee: 'Raju', slaMin: 60 },
      { id: 'bad-smell', name: 'Bad Smell / Odor', icon: '👃', dept: 'Housekeeping', assignee: 'Abu', slaMin: 30 },
      { id: 'dirty-area', name: 'Area Needs Cleaning', icon: '🧹', dept: 'Housekeeping', assignee: 'Abu', slaMin: 30 },
      { id: 'wet-floor', name: 'Wet Floor / Slippery', icon: '⚠️', dept: 'Housekeeping', assignee: 'Abu', slaMin: 15 },
      { id: 'light-issue', name: 'Light Not Working', icon: '💡', dept: 'Maintenance', assignee: 'Raju', slaMin: 60 },
      { id: 'noise', name: 'Excessive Noise', icon: '🔊', dept: 'Service', assignee: 'Amit', slaMin: 45 },
      { id: 'safety-hazard', name: 'Safety Hazard', icon: '🚨', dept: 'Maintenance', assignee: 'Raju', slaMin: 15 },
      { id: 'broken-item', name: 'Broken Furniture / Equipment', icon: '🪑', dept: 'Maintenance', assignee: 'Raju', slaMin: 60 },
    ],
  },
  'opd': {
    name: 'Outpatient Department',
    subtitle: 'OPD Wing',
    icon: '🏨',
    color: '#7c3aed',
    bg: '#f5f3ff',
    allowPhoto: true,
    allowFreeText: true,
    requireIdentification: false,
    categories: [
      { id: 'overcrowding', name: 'Overcrowding', icon: '👥', dept: 'Service', assignee: 'Amit', slaMin: 30 },
      { id: 'long-wait', name: 'Long Waiting Time', icon: '⏰', dept: 'Service', assignee: 'Amit', slaMin: 30 },
      { id: 'doctor-delay', name: 'Doctor Consultation Delay', icon: '👨‍⚕️', dept: 'Medical', assignee: 'Dr. Sharma', slaMin: 30 },
      { id: 'opd-dirty', name: 'Cleanliness Issue', icon: '🧹', dept: 'Housekeeping', assignee: 'Abu', slaMin: 30 },
      { id: 'staff-behavior', name: 'Staff Behavior', icon: '🙁', dept: 'Service', assignee: 'Amit', slaMin: 45 },
      { id: 'signage', name: 'Poor Signage / Directions', icon: '🪧', dept: 'Service', assignee: 'Amit', slaMin: 60 },
      { id: 'wheelchair-opd', name: 'Wheelchair Required', icon: '♿', dept: 'Service', assignee: 'Amit', slaMin: 15 },
      { id: 'ac-opd', name: 'AC / Temperature Issue', icon: '❄️', dept: 'Maintenance', assignee: 'Raju', slaMin: 60 },
    ],
  },
  'front-desk': {
    name: 'Front Desk',
    subtitle: 'Main Reception',
    icon: '🛎️',
    color: '#0891b2',
    bg: '#ecfeff',
    allowPhoto: false,
    allowFreeText: true,
    requireIdentification: false,
    categories: [
      { id: 'fd-wait', name: 'Long Wait Time', icon: '⏰', dept: 'Front Office', assignee: 'Anita', slaMin: 15 },
      { id: 'fd-behavior', name: 'Staff Behavior', icon: '🙁', dept: 'Front Office', assignee: 'Anita', slaMin: 45 },
      { id: 'fd-billing', name: 'Billing Confusion', icon: '💳', dept: 'Front Office', assignee: 'Anita', slaMin: 30 },
      { id: 'fd-directions', name: 'Need Directions', icon: '🗺️', dept: 'Front Office', assignee: 'Anita', slaMin: 10 },
      { id: 'fd-info', name: 'Information Not Available', icon: '❓', dept: 'Front Office', assignee: 'Anita', slaMin: 30 },
      { id: 'fd-insurance', name: 'Insurance Query', icon: '🛡️', dept: 'Front Office', assignee: 'Anita', slaMin: 45 },
    ],
  },
  'pharmacy': {
    name: 'Pharmacy',
    subtitle: 'Hospital Pharmacy Counter',
    icon: '💊',
    color: '#dc2626',
    bg: '#fef2f2',
    allowPhoto: true,
    allowFreeText: true,
    requireIdentification: true,
    categories: [
      { id: 'ph-wait', name: 'Long Wait Time', icon: '⏰', dept: 'Pharmacy', assignee: 'Ramesh', slaMin: 15 },
      { id: 'ph-unavailable', name: 'Medicine Not Available', icon: '❌', dept: 'Pharmacy', assignee: 'Ramesh', slaMin: 30 },
      { id: 'ph-wrong', name: 'Wrong Medicine Given', icon: '⚠️', dept: 'Pharmacy', assignee: 'Ramesh', slaMin: 10 },
      { id: 'ph-price', name: 'Pricing Issue', icon: '💰', dept: 'Pharmacy', assignee: 'Ramesh', slaMin: 30 },
      { id: 'ph-expired', name: 'Expired / Damaged Medicine', icon: '🚫', dept: 'Pharmacy', assignee: 'Ramesh', slaMin: 10 },
      { id: 'ph-behavior', name: 'Staff Behavior', icon: '🙁', dept: 'Pharmacy', assignee: 'Ramesh', slaMin: 45 },
    ],
  },
  'radiology': {
    name: 'Radiology',
    subtitle: 'Imaging & Diagnostics',
    icon: '🩻',
    color: '#4338ca',
    bg: '#eef2ff',
    allowPhoto: false,
    allowFreeText: true,
    requireIdentification: true,
    categories: [
      { id: 'rad-delay', name: 'Appointment Delay', icon: '⏰', dept: 'Diagnostics', assignee: 'Kavitha', slaMin: 30 },
      { id: 'rad-report', name: 'Report Delay', icon: '📋', dept: 'Diagnostics', assignee: 'Kavitha', slaMin: 60 },
      { id: 'rad-equipment', name: 'Equipment Issue', icon: '🔧', dept: 'Maintenance', assignee: 'Raju', slaMin: 45 },
      { id: 'rad-behavior', name: 'Staff Behavior', icon: '🙁', dept: 'Diagnostics', assignee: 'Kavitha', slaMin: 45 },
      { id: 'rad-comfort', name: 'Patient Comfort', icon: '🛋️', dept: 'Service', assignee: 'Amit', slaMin: 30 },
    ],
  },
  'billing': {
    name: 'Billing Counter',
    subtitle: 'Billing & Payments',
    icon: '💳',
    color: '#059669',
    bg: '#ecfdf5',
    allowPhoto: true,
    allowFreeText: true,
    requireIdentification: true,
    categories: [
      { id: 'bill-overcharge', name: 'Overcharging', icon: '💰', dept: 'Front Office', assignee: 'Anita', slaMin: 30 },
      { id: 'bill-wait', name: 'Long Wait Time', icon: '⏰', dept: 'Front Office', assignee: 'Anita', slaMin: 15 },
      { id: 'bill-insurance', name: 'Insurance Issue', icon: '🛡️', dept: 'Front Office', assignee: 'Anita', slaMin: 45 },
      { id: 'bill-receipt', name: 'Receipt Not Given', icon: '🧾', dept: 'Front Office', assignee: 'Anita', slaMin: 15 },
      { id: 'bill-error', name: 'Billing Error', icon: '❌', dept: 'Front Office', assignee: 'Anita', slaMin: 30 },
      { id: 'bill-behavior', name: 'Staff Behavior', icon: '🙁', dept: 'Front Office', assignee: 'Anita', slaMin: 45 },
    ],
  },
  'cafeteria': {
    name: 'Cafeteria',
    subtitle: 'Hospital Cafeteria',
    icon: '🍽️',
    color: '#ea580c',
    bg: '#fff7ed',
    allowPhoto: true,
    allowFreeText: true,
    requireIdentification: false,
    categories: [
      { id: 'caf-quality', name: 'Food Quality', icon: '👎', dept: 'FnB', assignee: 'Rohit Singh', slaMin: 30 },
      { id: 'caf-hygiene', name: 'Hygiene Issue', icon: '🧹', dept: 'FnB', assignee: 'Rohit Singh', slaMin: 15 },
      { id: 'caf-availability', name: 'Food Not Available', icon: '❌', dept: 'FnB', assignee: 'Rohit Singh', slaMin: 30 },
      { id: 'caf-price', name: 'Pricing Issue', icon: '💰', dept: 'FnB', assignee: 'Rohit Singh', slaMin: 45 },
      { id: 'caf-cleanliness', name: 'Dirty Tables / Area', icon: '🧽', dept: 'Housekeeping', assignee: 'Abu', slaMin: 20 },
      { id: 'caf-behavior', name: 'Staff Behavior', icon: '🙁', dept: 'FnB', assignee: 'Rohit Singh', slaMin: 45 },
    ],
  },
};

// ── PERSON QR CONFIGURATIONS ───────────────────────────────────────
// Each person card is fully configurable: name, title, and which options appear
export const PERSON_QR_MAP = {
  'unit-mgr-priya': {
    name: 'Priya',
    title: 'Unit Manager — Housekeeping',
    icon: '👩‍💼',
    color: '#7c3aed',
    photo: null,
    requireIdentification: true,
    categories: [
      { id: 'p-room-complaint', name: 'Room Not Clean', icon: '🧹', dept: 'Housekeeping', assignee: 'Priya', slaMin: 30 },
      { id: 'p-staff-complaint', name: 'Staff Behavior', icon: '🙁', dept: 'Housekeeping', assignee: 'Priya', slaMin: 30 },
      { id: 'p-linen-issue', name: 'Linen / Bedding Issue', icon: '🛏️', dept: 'Housekeeping', assignee: 'Priya', slaMin: 30 },
      { id: 'p-waste-mgmt', name: 'Waste Management', icon: '🗑️', dept: 'Housekeeping', assignee: 'Priya', slaMin: 30 },
      { id: 'p-pest-issue', name: 'Pest / Insect Issue', icon: '🐛', dept: 'Housekeeping', assignee: 'Priya', slaMin: 30 },
      { id: 'p-other', name: 'Other Concern', icon: '💬', dept: 'Housekeeping', assignee: 'Priya', slaMin: 45 },
    ],
    allowFreeText: true,
    allowPhoto: true,
    introMessage: 'I\'m Priya, your Unit Manager. Please share your concern and I\'ll personally ensure it\'s addressed.',
  },
  'ops-mgr-vinay': {
    name: 'Vinay Bhardwaj',
    title: 'Operations Manager',
    icon: '👨‍💼',
    color: '#1a6bf0',
    photo: null,
    requireIdentification: true,
    categories: [
      { id: 'v-service-issue', name: 'Service Delay', icon: '⏰', dept: 'Operations', assignee: 'Vinay Bhardwaj', slaMin: 30 },
      { id: 'v-staff-behavior', name: 'Staff Behavior', icon: '🙁', dept: 'Operations', assignee: 'Vinay Bhardwaj', slaMin: 30 },
      { id: 'v-process-issue', name: 'Process / System Issue', icon: '⚙️', dept: 'Operations', assignee: 'Vinay Bhardwaj', slaMin: 45 },
      { id: 'v-food-quality', name: 'Food Quality', icon: '🍽️', dept: 'Operations', assignee: 'Vinay Bhardwaj', slaMin: 30 },
      { id: 'v-facility', name: 'Facility Issue', icon: '🏥', dept: 'Operations', assignee: 'Vinay Bhardwaj', slaMin: 45 },
      { id: 'v-safety', name: 'Safety Concern', icon: '🚨', dept: 'Operations', assignee: 'Vinay Bhardwaj', slaMin: 15 },
      { id: 'v-compliment', name: 'Compliment / Appreciation', icon: '⭐', dept: 'Operations', assignee: 'Vinay Bhardwaj', slaMin: 0 },
      { id: 'v-other', name: 'Other Concern', icon: '💬', dept: 'Operations', assignee: 'Vinay Bhardwaj', slaMin: 45 },
    ],
    allowFreeText: true,
    allowPhoto: true,
    introMessage: 'I\'m Vinay, the Operations Manager at Even Hospital. Your feedback matters — please share your experience.',
  },
  'admin-chandrika': {
    name: 'Chandrika',
    title: 'Hospital Administrator',
    icon: '👩‍⚕️',
    color: '#dc2626',
    photo: null,
    requireIdentification: true,
    categories: [
      { id: 'c-escalation', name: 'Unresolved Issue', icon: '🔴', dept: 'Admin', assignee: 'Chandrika', slaMin: 30 },
      { id: 'c-medical', name: 'Medical Care Concern', icon: '👨‍⚕️', dept: 'Admin', assignee: 'Chandrika', slaMin: 30 },
      { id: 'c-safety', name: 'Patient Safety', icon: '🚨', dept: 'Admin', assignee: 'Chandrika', slaMin: 15 },
      { id: 'c-discharge', name: 'Discharge Issue', icon: '📋', dept: 'Admin', assignee: 'Chandrika', slaMin: 30 },
      { id: 'c-compliment', name: 'Compliment / Appreciation', icon: '⭐', dept: 'Admin', assignee: 'Chandrika', slaMin: 0 },
      { id: 'c-other', name: 'Other Concern', icon: '💬', dept: 'Admin', assignee: 'Chandrika', slaMin: 45 },
    ],
    allowFreeText: true,
    allowPhoto: true,
    introMessage: 'I\'m Chandrika, the Hospital Administrator. Please share your concern — I\'ll ensure it gets the attention it deserves.',
  },
};

// ── DEPARTMENT QR (internal staff use) ─────────────────────────────
export const DEPT_QR_MAP = {
  'nursing-station-2': {
    name: 'Nursing Station',
    subtitle: '2nd Floor',
    icon: '👩‍⚕️',
    color: '#0891b2',
    requireIdentification: true,
    categories: [
      { id: 'ns-supply', name: 'Supply Needed', icon: '📦', dept: 'Service', assignee: 'Amit', slaMin: 30 },
      { id: 'ns-equipment', name: 'Equipment Issue', icon: '🔧', dept: 'Maintenance', assignee: 'Raju', slaMin: 30 },
      { id: 'ns-cleaning', name: 'Cleaning Required', icon: '🧹', dept: 'Housekeeping', assignee: 'Abu', slaMin: 30 },
      { id: 'ns-it', name: 'IT / System Issue', icon: '💻', dept: 'Maintenance', assignee: 'Raju', slaMin: 45 },
      { id: 'ns-pharmacy', name: 'Pharmacy Delay', icon: '💊', dept: 'Pharmacy', assignee: 'Ramesh', slaMin: 20 },
    ],
    allowFreeText: true,
    allowPhoto: true,
  },
  'lab-counter': {
    name: 'Laboratory',
    subtitle: 'Sample Collection Counter',
    icon: '🔬',
    color: '#7c3aed',
    requireIdentification: true,
    categories: [
      { id: 'lab-supply', name: 'Supply Needed', icon: '📦', dept: 'Service', assignee: 'Amit', slaMin: 30 },
      { id: 'lab-equipment', name: 'Equipment Malfunction', icon: '🔧', dept: 'Maintenance', assignee: 'Raju', slaMin: 30 },
      { id: 'lab-cleaning', name: 'Cleaning Required', icon: '🧹', dept: 'Housekeeping', assignee: 'Abu', slaMin: 30 },
      { id: 'lab-it', name: 'System / LIMS Issue', icon: '💻', dept: 'Maintenance', assignee: 'Raju', slaMin: 30 },
    ],
    allowFreeText: true,
    allowPhoto: true,
  },
};
